name: Linting

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' #required for npm 8 or later.
    - run: npm install
    - run: npm run lint
      env:
        CI: true
